### Pytorch basics

In [2]:
import torch
torch.__version__

'1.8.2+cu102'

In [5]:
### Empty tensors

# x = torch.empty(2)
# x = torch.empty(2,8,3)
x = torch.empty(5,5)
# x = torch.empty(2,2,3)
print(x)
print(x.shape)

tensor([[6.9362e-07, 6.5930e-10, 4.3442e-05, 1.3034e+16, 2.1707e-18],
        [7.0952e+22, 1.7748e+28, 1.8176e+31, 7.2708e+31, 5.0778e+31],
        [3.2608e-12, 1.7728e+28, 7.0367e+22, 2.1715e-18, 2.0663e+20],
        [6.8997e-07, 2.6433e-06, 4.2957e-05, 4.1298e-05, 1.0414e-11],
        [1.7107e-04, 1.6877e-07, 1.6986e+22, 2.1707e-18, 7.1450e+31]])
torch.Size([5, 5])


In [7]:
### Random tensors

# x = torch.rand(2)
# x = torch.rand(2,8,3)
# x = torch.rand(5,5)
x = torch.rand(2,2,3)
print(x)
print(x.shape)

tensor([[[0.3458, 0.6988, 0.1811],
         [0.3133, 0.1766, 0.1435]],

        [[0.8260, 0.9817, 0.7923],
         [0.5214, 0.1541, 0.1644]]])
torch.Size([2, 2, 3])


In [12]:
# x = torch.zeros(2)
# x = torch.ones(2,8,3)
# x = 5*torch.ones(5,5)
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


### Elemen-wise operations

In [20]:
### Addition

x = torch.rand(2,2)
y = torch.rand(2,2)
z = torch.add(x,y) ## ==> x+y
# y.add_(x)          ### ubdate y by adding x

print("x tessor is:\n ", x)
print("y tessor is:\n ", y)
print("z tessor is:\n ", z)

x tessor is:
  tensor([[0.1579, 0.0310],
        [0.8617, 0.6397]])
y tessor is:
  tensor([[0.6794, 0.3288],
        [0.2172, 0.9229]])
z tessor is:
  tensor([[0.8373, 0.3598],
        [1.0788, 1.5626]])


In [23]:
### Substuction

x = torch.rand(2,2)
y = torch.rand(2,2)
z = torch.sub(x,y) ## ==> x-y
# y.sub_(x)          ### ubdate y by substracting x

print("x tessor is:\n ", x)
print("y tessor is:\n ", y)
print("z tessor is:\n ", z)

x tessor is:
  tensor([[0.6574, 0.5210],
        [0.0273, 0.1048]])
y tessor is:
  tensor([[0.9981, 0.8227],
        [0.0267, 0.7947]])
z tessor is:
  tensor([[-3.4071e-01, -3.0179e-01],
        [ 5.1957e-04, -6.8988e-01]])


In [25]:
### Multiplication

x = torch.rand(2,2)
y = torch.rand(2,2)
z = torch.mul(x,y) ## ==> x*y
# y.mul_(x)          ### ubdate y by multiplaying x

print("x tessor is:\n ", x)
print("y tessor is:\n ", y)
print("z tessor is:\n ", z)

x tessor is:
  tensor([[0.8288, 0.5756],
        [0.1871, 0.8033]])
y tessor is:
  tensor([[0.4283, 0.5330],
        [0.0190, 0.4080]])
z tessor is:
  tensor([[0.4283, 0.5330],
        [0.0190, 0.4080]])


In [27]:
### Division
x = torch.rand(2,2)
y = torch.rand(2,2)
z = torch.div(x,y) ## ==> x/y
# y.div_(x)          ### ubdate y by dividing x ==> y = y/x

print("x tessor is:\n ", x)
print("y tessor is:\n ", y)
print("z tessor is:\n ", z)

x tessor is:
  tensor([[0.4852, 0.4915],
        [0.5165, 0.9855]])
y tessor is:
  tensor([[1.6263, 1.9076],
        [1.9038, 0.3470]])
z tessor is:
  tensor([[0.6149, 0.5242],
        [0.5253, 2.8822]])


### Autograd  Gradient Computation

In [31]:
import torch

x = torch.rand(3, requires_grad=True)
print(x)
y = x+2
print(y)
z = y*y*2
z = z.mean()
print(z)
z.backward()  ## dz/dx
print(x.grad)

tensor([0.6308, 0.1548, 0.8546], requires_grad=True)
tensor([2.6308, 2.1548, 2.8546], grad_fn=<AddBackward0>)
tensor(13.1420, grad_fn=<MeanBackward0>)
tensor([3.5078, 2.8731, 3.8061])


In [34]:
x = torch.rand(3, requires_grad=True)
print(x)
x.requires_grad_(False)
y = x+2
print(y)

tensor([0.8563, 0.0638, 0.0219], requires_grad=True)
tensor([2.8563, 2.0638, 2.0219])


### Backpropagation